export const JWT_PUBLIC_KEY = process.env.JWT_PUBLIC_KEY || `-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA6dEcVZXpWKNndsTPYDCF
jwlHcAzZJzElhD1IRg9aCry+C/qvSs8yoARjs9hFHgLM41LXAC7Au+w+NHrcNsWR
mT6qrl05GaDAlvlHFGwPZ4CiE5Ld1fxei4uqNlmhZqNFRjQdGXlM6YyH87qzh45q
A8HHx6TFpoY1W5HGZgMFc49osDD03kmeQFHqy7QUvSrKuLMdsWt+dWyXU6UBYiCy
m5BXqHJd+hyS64rMrbHVHrDBrrCpWYtbpH6rttvXcfiENu52kbPPsys4OKKJ253P
ZLvXXpb0/K+NwKg+epCxHcnvRxkEMYKdB/cFupY6efdXPSgUyP6wXev7s5D9gYOD
JwIDAQAB
-----END PUBLIC KEY-----
`;